name: Runs CMake
description: Runs CMake
inputs:
  compiler:
    description: compiler to run on (either clang or gcc)
    required: false
  options:
    description: extra options for to run cmake with
    required: false
runs:
  using: "composite"
  steps:
  - name: Execute the CMake Instructions
    run: |
        if [ "${{inputs.compiler}}" = "clang" ]; then
          export CC=clang && export CXX=clang++
        elif [ "${{inputs.compiler}}" = "gcc" ]; then
          export CC=gcc && export CXX=g++
        fi
        mkdir build
        cd build
        cmake ${{inputs.options}} ..
    shell: bash
  