name: Builds CMake
description: Runs CMake
inputs:
  compiler:
    description: compiler to run on (either clang or gcc)
    required: false
  options:
    description: extra options for to run the bazel with
    required: false
runs:
  using: "composite"
  steps:
  - name: Execute the Bazel Build
    run: |
        if [ "${{inputs.compiler}}" = "clang" ]; then
          export CC=clang && export CXX=clang++
        elif [ "${{inputs.compiler}}" = "gcc" ]; then
          export CC=gcc && export CXX=g++
        fi

        bazel build -j ${{env.proc_num}} -c opt --copt -DHAVE_ZLIB=1 ${{inputs.options}} //...
        
    shell: bash